### ISSUE TITLE
duplicate feature runs when default feature defined

### ISSUE THREAD

**Issue by leighmcculloch** [taiki-e/cargo-hack#155]
When I use `cargo hack --feature-power` with a crate that has a `default` feature defined, cargo-hack runs the default feature set, as well as the features defined in the default feature set, and the same feature set is run twice.

For example, with the following features defined:
```toml
[features]
default = ["std"]
std = ["alloc"]
alloc = []
```

A `cargo hack --feature-powerset` will run the following combinations:
```
❯ cargo hack check --feature-powerset 2>&1 | grep 'info:'
info: running `cargo check --no-default-features` on ... (1/4)
info: running `cargo check --no-default-features --features alloc` on ... (2/4)
info: running `cargo check --no-default-features --features default` on ... (3/4)
info: running `cargo check --no-default-features --features std` on ... (4/4)
```

The `std` and `default` feature set are the same, and yet it runs them both. This problem has a larger impact when more feature sets are defined where many jobs are repeated.

It would be ideal if the feature powerset feature identified when the default and another featureset overlap, and then only run one of them. For example, it would be ideal if the above command resulted in the following output:

```
❯ cargo hack check --feature-powerset 2>&1 | grep 'info:'
info: running `cargo check --no-default-features` on ... (1/3)
info: running `cargo check --no-default-features --features alloc` on ... (2/3)
info: running `cargo check --no-default-features --features std` on ... (3/3)
```

**Comment by taiki-e** [comment]
No. If `default = [...]` is defined in `features` section, Cargo sets `#[cfg(feature = "default")]` when default features are enabled, so it is not equal to --no-default-features + --features=std. (e.g., [async-std uses it](https://github.com/async-rs/async-std/blob/ca8305064bee7d27f0b9e98c30825dbfe3da8468/src/utils.rs#L6))

**Comment by taiki-e** [comment]
As discussed in https://github.com/taiki-e/cargo-hack/issues/81, cargo-hack deduplicates any fully equivalent feature combinations based on how the cargo features work.
On the other hand, determining that `--features=default` and `--features=std` are equivalent in your case, probably requires something like a heuristic that excludes feature combinations based on how cfg is actually used. (I think it is probably very hard to implement it properly and it takes time because it is necessary to scan all the codes.)

If you can guarantee that default and std features are exactly the same, the currently recommended approach is to use the `--exclude-features` option to exclude `--features=default`.
If your crate has many features, the currently recommended approach is to use the `--depth` option to limit the maximum number of simultaneous feature flags of `--feature-powerset` (https://github.com/taiki-e/cargo-hack/issues/58).

**Comment by leighmcculloch** [comment]
Ah. I had erroneously believed that default was a special feature and that it didn't actually materialize as a feature in cfgs. Thank you for the detailed explanation.

**Comment by leighmcculloch** [comment]
> (I think it is probably very hard to implement it properly and it takes time because it is necessary to scan all the codes.)

Agreed. This would likely be a capability fraught with endless edge cases. I think cargo-hack is balancing the complexity to benefit spectrum well as it is.

**Comment by JoseSK999** [comment]
Hi @taiki-e

So if we don't use `[cfg(feature = "default")]` and our `default` feature is just listing other features we have, it should be fine to `--exclude-features default` right? The resulting feature combinations will include the `default` case.

**Comment by JoseSK999** [comment]
Wow thanks for the super quick answer! I understand the complexity better now
