### ISSUE TITLE
`--feature-powerset` crashes `cargo-hack` and my terminal

### ISSUE THREAD

**Issue by thomaseizinger** [taiki-e/cargo-hack#227]
I'd like to adopt `cargo-hack` for testing a feature matrix of the `libp2p` facade crate, see https://github.com/libp2p/rust-libp2p.

Unfortunately, I can't seem to get it to work. I've tried to following locally:

```sh
cargo hack --package libp2p check --feature-powerset
```

This hangs for a few seconds and then crashes my terminal (Alacritty). The `libp2p` crate does have a few features (~40). Is that a problem?

If I resort to `--each-feature`, it starts compiling the crate. However, I'd like to use `--at-least-one-of` and that seems to be only compatible with `--feature-powerset`.

Let me know how I can provide more debug information or whether you can reproduce that locally.

**Comment by taiki-e** [comment]
Thanks for the report. The problem is OOM due to too many feature combinations.

In your case, this can be worked around by `--depth` option with a value smaller than 8 or 9.

Btw, with --depth 8, there are 51738694 feature combinations.

I think this is a reasonable limitation since it is not realistic to actually check such a large number of combinations (although should report error instead of crashing), but improving [the implementation of the powerset calculation](https://github.com/taiki-e/cargo-hack/blob/5dfe0b4ca599441b5c13b84ee3b35a381a3f64fb/src/features.rs#L180-L252) may reduce memory usage.

**Comment by thomaseizinger** [comment]
Ah I see :sweat_smile: 

I guess what I want is `--depth 1` but being able to use `--at-least-one-of`!
