### ISSUE TITLE
Missing Cargo.lock file

### ISSUE THREAD

**Issue by jjanowsk** [taiki-e/cargo-hack#263]
Hi! 
Is there a reason why this repo does not contain a Cargo.lock file? Even your README recommends using `cargo +stable install cargo-hack --locked` to install cargo-hack from source. We recently had an issue in our CI where the installation of cargo-hack stopped working because the new version of one of your dependencies started to require a newer version of rust. It would have been prevented with a Cargo.lock.

**Comment by taiki-e** [comment]
See https://github.com/taiki-e/cargo-hack/pull/117 & https://github.com/taiki-e/cargo-llvm-cov/pull/152.

TR;DR: 
Cargo.lock is automatically published to crates.io.
Therefore, your problem is that you did not install in the way recommended in the readme and has nothing to do with the fact that this repository has not committed the lockfile.
