### ISSUE TITLE
Option to clean between each run

### ISSUE THREAD

**Issue by Nemo157** [taiki-e/cargo-hack#47]
I'm attempting to use `cargo hack test --feature-powerset` on a project, but given the sheer number of combinations this results in exceeding the available disk space on Github Actions with all the resulting test binaries.

If it were possible to run `cargo clean -p <project>` between each test run, that would delete the test binaries but leave the precompiled dependencies behind. It's probably not wanted as the default since it would slow down rerunning `cargo hack --feature-powerset` locally when you are able to cache all the results, but being an option would be very useful for CI.

**Comment by Nemo157** [comment]
(Though TBH I think given the 512 feature combinations in this project I won't be able to use `test --feature-powerset` in CI anyway because of the time it takes, but maybe this would be useful for other projects that are closer to being able to run the full set except for disk space issues).

**Comment by taiki-e** [comment]
It may not always be enough in a project where features fine control over dependencies' features, but I think this option is useful to some extent for this use case.

Also, I think this might help as a workaround for https://github.com/rust-lang/rust-clippy/issues/4612. (Probably makes sense to run `cargo clean -p` "before each run" rather than "between each run".)

<br>

> (Though TBH I think given the 512 feature combinations in this project I won't be able to use `test --feature-powerset` in CI anyway because of the time it takes, but maybe this would be useful for other projects that are closer to being able to run the full set except for disk space issues).

AFAIK, if features are additive, then the test only needs to run with `--all-features` once.

Also, If check [if the test compile under all `--feature` combinations](https://github.com/rust-lang/futures-rs/pull/2101), it doesn't need to actually run the test and  I think `check --all-targets` or `test --no-run` is fine. (This probably needs to be separated from checking of the library/binary itself, as dev-dependencies may enable features.)

If features are non-additive, ideally it is preferable to run the test for each feature, but `test --feature-powerset` takes too long, so there is probably no way yet to do this easily. (However, I don't think such features are good for libraries in many cases, as other dependencies may enable it.)
Making `--skip` works for `--all-features` is probably one of the reasonable solutions for this. If one feature is non-additive and other features are additive (e.g., [using different implementations between std and no-std](https://github.com/serde-rs/serde/issues/918)), I think this is enough.

**Comment by Nemo157** [comment]
> This probably needs to be separated from checking of the library/binary itself, as dev-dependencies may enable features.

Ah, that's a good point. I had reduced my usage to running `check --all-targets` for the feature-sets since that _only_ takes 18 minutes, and only running the tests once with `--all-features`, but didn't think about having to still have a separate `check --all-targets --no-dev-deps`.

**Comment by taiki-e** [comment]
Published in 0.3.11 (#49)
